version: '3'
services:
  gis-database:
    ports:
      - 15432:5432
    build:
      context: ./Database
      dockerfile: Dockerfile
    volumes:
      - gis-db:/var/lib/postgresql
      - ./Database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=gis_user
      - PGADMIN_DEFAULT_PASSWORD=gis_pass
    ports:
      - 8080:80
    volumes: 
      - ./Database/servers.json:/pgadmin4/servers.json

  gis-backend:
    ports:
      - 5000:5000
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/:/var/opt/gis/

  gis-frontend:
    ports:
      - 4200:4200
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/gis:/var/opt/gis/
    command: sh -c "npm install && npm run start:docker"

volumes: 
  gis-db:
    driver: local
